### ISSUE TITLE
linker error when build with epics 7.0.4 on windows 10, windows-x64 static build

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-modules/script#20]
**Describe the issue**

**Steps to reproduce**
1. epics base 7.0.4\CONFIG_SITE: 
SHARED_LIBRARIES=NO
# Build client objects statically.
#  Must be either YES or NO.
STATIC_BUILD=YES
2. compile epics base 7.0.4 with static settings in step 1
3. compile LUA.

**Expected behaivour**
build with no error
**Actual behaviour**
"Installing library ../../../lib/windows-x64/lua.lib"
cl -EHsc -GR           -DLUA_BUILD_AS_DLL -DUSE_TYPED_RSET     -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3 -w44355 -w44344 -w44251     -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING    -MT  -TP  -I. -I../O.Common -I. -I. -I.. -I../../../luaApp/src/core -I../../../luaApp/src/devSupport -I../../../luaApp/src/rec -I../../../luaApp/src/shell -I../../../luaApp/src/portdriver -I../../../luaApp/src/libs -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include   -IC:/epics/modules/synApps_6_1_epics7/support/include   -IC:/epics/modules/synApps_6_1_epics7/support/asyn-R4-38/include -IC:/epics/base-7.0.4/include/compiler/msvc -IC:/epics/base-7.0.4/include/os/WIN32 -IC:/epics/base-7.0.4/include        -c testLuaIoc_registerRecordDeviceDriver.cpp
testLuaIoc_registerRecordDeviceDriver.cpp
cl           -DLUA_BUILD_AS_DLL -DUSE_TYPED_RSET     -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3     -DLUA_BUILD_AS_DLL    -MT    -I. -I../O.Common -I. -I. -I.. -I../../../luaApp/src/core -I../../../luaApp/src/devSupport -I../../../luaApp/src/rec -I../../../luaApp/src/shell -I../../../luaApp/src/portdriver -I../../../luaApp/src/libs -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include   -IC:/epics/modules/synApps_6_1_epics7/support/include   -IC:/epics/modules/synApps_6_1_epics7/support/asyn-R4-38/include -IC:/epics/base-7.0.4/include/compiler/msvc -IC:/epics/base-7.0.4/include/os/WIN32 -IC:/epics/base-7.0.4/include        -c ../luaMain.c
luaMain.c
link -nologo  -LTCG -incremental:no -opt:ref -release  -MACHINE:X64              -out:testLuaIoc.exe   testLuaIoc_registerRecordDeviceDriver.obj luaMain.obj     ../../../lib/windows-x64/lua.lib  C:/epics/modules/synApps_6_1_epics7/support/asyn-R4-38/lib/windows-x64/asyn.lib  C:/epics/base-7.0.4/lib/windows-x64/dbRecStd.lib  C:/epics/base-7.0.4/lib/windows-x64/dbCore.lib  C:/epics/base-7.0.4/lib/windows-x64/ca.lib  C:/epics/base-7.0.4/lib/windows-x64/Com.lib  netapi32.lib ws2_32.lib advapi32.lib user32.lib kernel32.lib winmm.lib dbghelp.lib
lua.lib(devLuaLongin.obj) : error LNK2001: unresolved external symbol __imp_lua_type
lua.lib(devLuaLongin.obj) : error LNK2001: unresolved external symbol __imp_lua_tointegerx
lua.lib(devLuaLongin.obj) : error LNK2001: unresolved external symbol __imp_lua_isinteger
lua.lib(devLuaLongin.obj) : error LNK2001: unresolved external symbol __imp_lua_getglobal
lua.lib(devLuaLongin.obj) : error LNK2001: unresolved external symbol __imp_lua_settop
lua.lib(devLuaAi.obj) : error LNK2001: unresolved external symbol __imp_lua_tonumberx
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_pushinteger
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_pcallk
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_rotate
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_concat
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_createtable
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_len
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_setglobal
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_tolstring
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_luaL_loadbufferx
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_geti
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_pushstring
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_pushnumber
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_gettop
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_close
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_rawseti
lua.lib(luascriptRecord.obj) : error LNK2001: unresolved external symbol __imp_lua_pushvalue
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_pushcclosure
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_loadfilex
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_traceback
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_pushlightuserdata
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_callmeta
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_error
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_topointer
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_pushfstring
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_sethook
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_checkstack
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_luaL_requiref
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_getfield
lua.lib(luaShell.obj) : error LNK2001: unresolved external symbol __imp_lua_typename
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_isnumber
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_checklstring
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_checktype
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_setfield
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_next
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_checkinteger
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_setmetatable
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_setfuncs
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_isstring
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_touserdata
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_checknumber
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_checkversion_
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_toboolean
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_luaL_newmetatable
lua.lib(lasynlib.obj) : error LNK2001: unresolved external symbol __imp_lua_pushnil
lua.lib(luaPortDriver.obj) : error LNK2001: unresolved external symbol __imp_luaL_loadstring
lua.lib(luaPortDriver.obj) : error LNK2001: unresolved external symbol __imp_lua_seti
lua.lib(luaPortDriver.obj) : error LNK2001: unresolved external symbol __imp_luaL_optinteger
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_lua_getmetatable
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_luaL_newstate
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_lua_pushboolean
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_lua_error
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_lua_setmetatable
lua.lib(luaEpics.obj) : error LNK2001: unresolved external symbol __imp_luaL_openlibs
testLuaIoc.exe : fatal error LNK1120: 59 unresolved externals
gmake[3]: *** [C:/epics/base-7.0.4/configure/RULES_BUILD:213: testLuaIoc.exe] Error 1120
gmake[3]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/lua-R3-0-1/luaApp/src/O.windows-x64'
gmake[2]: *** [C:/epics/base-7.0.4/configure/RULES_ARCHS:58: install.windows-x64] Error 2
gmake[2]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/lua-R3-0-1/luaApp/src'
gmake[1]: *** [C:/epics/base-7.0.4/configure/RULES_DIRS:85: src.install] Error 2
gmake[1]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/lua-R3-0-1/luaApp'
gmake: *** [C:/epics/base-7.0.4/configure/RULES_DIRS:85: luaApp.install] Error 2
**Build Environment**
Architecture: windows-x64
Epics Base Version:7.0.4
Dependent Module Versions:LUA3.0.1

**Comment by MarkRivers** [comment]
EPICS base provides a separate architecture for static builds on Windows, windows-x64-static.  I just tested building the master branch of lua with that architecture and it worked fine.

```
J:\epics\devel\lua>set EPICS_HOST_ARCH
EPICS_HOST_ARCH=windows-x64-static

J:\epics\devel\lua>make -sj clean

J:\epics\devel\lua>make -sj
luaEpics.cpp
lapi.c
lauxlib.c
lcode.c
lctype.c
lcorolib.c
lbitlib.c
lbaselib.c
ldblib.c
ldebug.c
lfunc.c
ldump.c
lgc.c
ldo.c
linit.c
lmathlib.c
liolib.c
llex.c
loadlib.c
loslib.c
lobject.c
lparser.c
lmem.c
lstate.c
lstring.c
lopcodes.c
lstrlib.c
ltable.c
lundump.c
ltm.c
lvm.c
ltablib.c
devLuaAi.c
devLuaBi.c
lzio.c
devLuaAo.c
lutf8lib.c
devLuaBo.c
devLuaLongin.c
devLuaMbbo.c
devLuaMbbi.c
devLuaLongout.c
j:\epics\devel\lua\luaapp\src\devsupport\devluabi.c(41): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
devLuaStringin.c
j:\epics\devel\lua\luaapp\src\devsupport\devluambbi.c(42): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
luaSoft.c
lasynlib.cpp
ldatabaselib.cpp
devUtil.cpp
devLuaStringout.c
j:\epics\devel\lua\luaapp\src\devsupport\devlualongin.c(40): warning C4244: 'initializing': conversion from 'lua_Integer' to 'long', possible loss of data
lepicslib.cpp
luaMain.c
luaShell.cpp
luashMain.cpp
testLuaIoc_registerRecordDeviceDriver.cpp
luascriptRecord.cpp
testLuaShell_registerRecordDeviceDriver.cpp
j:\epics\devel\lua\luaapp\src\rec\luascriptrecord.cpp(630): warning C4800: 'double': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\rec\luascriptrecord.cpp(303): warning C4244: 'argument': conversion from 'epicsFloat32' to 'lua_Integer', possible loss of data
j:\epics\devel\lua\luaapp\src\rec\luascriptrecord.cpp(375): note: see reference to function template instantiation 'int createTable<epicsFloat32>(lua_State *,DBLINK *,short,long *,bool)' being compiled
j:\epics\devel\lua\luaapp\src\luaepics.cpp(211): warning C4244: 'initializing': conversion from 'lua_Number' to 'int', possible loss of dataj:\epics\devel\lua\luaapp\src\rec\luascriptrecord.cpp(303): warning C4244: 'argument': conversion from 'epicsFloat64' to 'lua_Integer', possible loss of data

j:\epics\devel\lua\luaapp\src\rec\luascriptrecord.cpp(379): note: see reference to function template instantiation 'int createTable<epicsFloat64>(lua_State *,DBLINK *,short,long *,bool)' being compiled
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(129): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(156): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(187): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(188): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(201): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(274): warning C4244: 'initializing': conversion from 'lua_Integer' to 'epicsInt32', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(385): warning C4244: 'initializing': conversion from 'lua_Integer' to 'epicsInt32', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(464): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(480): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(496): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(512): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(564): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(649): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(654): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(666): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(685): warning C4244: '=': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(690): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(702): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(771): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(779): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(791): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(810): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(818): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(830): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(849): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(902): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(911): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(954): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(982): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(1000): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
j:\epics\devel\lua\luaapp\src\libs\lasynlib.cpp(1016): warning C4244: 'initializing': conversion from 'lua_Integer' to 'int', possible loss of data
Appending ldatabaselib.obj
Appending lepicslib.obj
Appending lasynlib.obj
Appending luaShell.obj
Appending luaSoft.obj
Appending luascriptRecord.obj
Appending devUtil.obj
Appending devLuaStringout.obj
Appending devLuaStringin.obj
Appending devLuaLongout.obj
Appending devLuaLongin.obj
Appending devLuaMbbo.obj
Appending devLuaMbbi.obj
Appending devLuaBo.obj
Appending devLuaBi.obj
Appending devLuaAo.obj
Appending devLuaAi.obj
Appending lzio.obj
Appending lvm.obj
Appending lutf8lib.obj
Appending lundump.obj
Appending ltm.obj
Appending ltablib.obj
Appending ltable.obj
Appending lstrlib.obj
Appending lstring.obj
Appending lstate.obj
Appending lparser.obj
Appending loslib.obj
Appending lopcodes.obj
Appending lobject.obj
Appending loadlib.obj
Appending lmem.obj
Appending lmathlib.obj
Appending llex.obj
Appending liolib.obj
Appending linit.obj
Appending lgc.obj
Appending lfunc.obj
Appending ldump.obj
Appending ldo.obj
Appending ldebug.obj
Appending ldblib.obj
Appending lctype.obj
Appending lcorolib.obj
Appending lcode.obj
Appending lbitlib.obj
Appending lbaselib.obj
Appending lauxlib.obj
Appending lapi.obj
Appending luaEpics.obj

J:\epics\devel\lua>dir bin\windows-x64-static
 Volume in drive J is people_rw
 Volume Serial Number is 1FC2-CD09

 Directory of J:\epics\devel\lua\bin\windows-x64-static

12/31/2020  07:22 AM    <DIR>          .
07/08/2020  03:51 PM    <DIR>          ..
12/31/2020  07:22 AM         2,275,840 testLuaIoc.exe
12/31/2020  07:22 AM         2,275,840 testLuaShell.exe
               2 File(s)      4,551,680 bytes
               2 Dir(s)  219,507,589,120 bytes free
```

**Comment by MarkRivers** [comment]
It is a good idea to use the architecture windows-x64 for dynamic builds and windows-x64-static for static builds.  That way you can build both in the same tree.

**Comment by LeeYangLBLBCS** [comment]
build succeeded with target=windows-x64-static.
thanks.
